apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    kustomize.toolkit.fluxcd.io/name: nginx-deploy
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
status:
  loadBalancer: {}
